// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ystyidtouxonrtuxtjrh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlzdHlpZHRvdXhvbnJ0dXh0anJoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY1ODQ4MzksImV4cCI6MjA1MjE2MDgzOX0.1pOmfm_ytwapA1tz9tlWF_l98adgKKAXMPOodrfPSqY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);